* Making Research Reproducible  
** Preamble                                                     :ignore:
*** General comments                                                 :ignore:
# ----------------------------------------------------------------------
# README.org
#
# created on Wed Oct 10 16:35:39 2018
# Philipp Homan, <phoman1 at northwell dot edu>
# ----------------------------------------------------------------------
*** org specific settings                                            :ignore:
# ----------------------------------------------------------------------
#+OPTIONS: email:nil toc:nil num:nil author:nil date:t tex:t
#+STARTUP: align fold
#+SEQ_TODO: TODO(t) | DONE(d)
#+TAGS: figure(f) check(c) noexport(n) ignore(i)
#+LANGUAGE: en
#+EXCLUDE_TAGS: noexport TODO
#+DATE: {{{time(%Y-%m-%d %H:%M)}}}
# ----------------------------------------------------------------------
*** Buffer-wide source code blocks                                   :ignore:
# ----------------------------------------------------------------------
# Set elisp variables need for nice formatting We want no new lines in
# inline results and a paragraph size of 80 characters Important: this
# has to be evaluated witch C-c C-c in order to work in the current
# buffer
#+BEGIN_SRC emacs-lisp :exports none :results silent

; set timestamp format
;(setq org-export-date-timestamp-format "%ft%t%z")
(require 'org-wc)
(flyspell-mode t)
(synosaurus-mode t)
(auto-complete-mode t)
(linum-mode t)
(whitespace-mode t)
(setq org-babel-inline-result-wrap "%s")
(setq org-export-with-broken-links "mark")
(setq fill-column 72)
(setq whitespace-line-column 72)
;(setq org-latex-caption-above '(table image))
(setq org-latex-caption-above nil)
(org-toggle-link-display)
; don't remove logfiles at export
(setq org-latex-remove-logfiles nil)

; keybindings
; (global-set-key (kbd "<f7> c") "#+CAPTION: ")
(defun setfillcolumn72 ()
	(interactive)
	(setq fill-column 72)
)

(defun setfillcolumn42 ()
	(interactive)
	(setq fill-column 42)
)
(define-key org-mode-map (kbd "C-c #") "#+CAPTION: ")
(define-key org-mode-map (kbd "C-c f c 4 2") 'setfillcolumn42)
(define-key org-mode-map (kbd "C-c f c 7 2") 'setfillcolumn72)

(setq org-odt-category-map-alist
	 '(("__figure__" "*figure*" "value" "figure" org-odt--enumerable-image-p)))

; let ess not ask for starting directory
(setq ess-ask-for-ess-directory nil)

;(setq org-latex-pdf-process '("latexmk -pdflatex='xelatex
;-output-directory=../output/tex/ -interaction nonstopmode' -pdf
;-bibtex -f %f"))

;(setq org-latex-pdf-process '("latexmk -pdf 
;	-pdflatex='xelatex -shell-escape -interaction nonstopmode' -bibtex -f %f "))
(setq org-latex-pdf-process '("latexmk -pdflatex='xelatex -interaction nonstopmode' -shell-escape -pdf -bibtex -f %f"))

(setq org-latex-logfiles-extensions 
	 (quote("bcf" "blg" "fdb_latexmk" "fls" 
	 "figlist" "idx" "log" "nav" "out" "ptc" 
	 "run.xml" "snm" "toc" "vrb" "xdv")))

(add-to-list 'org-structure-template-alist
 '("ca" "#+CAPTION: "))

(add-to-list 'org-structure-template-alist
 '("he" "#+LATEX_HEADER: "))

(add-to-list 'org-structure-template-alist
 '("dc" "src_R[:session]{}"))

(add-to-list 'org-structure-template-alist
 '("sr" "#+HEADER: :exports none
,#+begin_src R :colnames yes :results silent :session\n")) 

(add-to-list 'org-structure-template-alist
 '("er" "#+END_SRC"))

 #+END_SRC
 # ----------------------------------------------------------------------
 # End preamble
 # ----------------------------------------------------------------------
 # Start with doublespacing 
 \doublespacing
 \clearpage

*** End preamble                                               :ignore:
# ----------------------------------------------------------------------
** Code                                                :noexport:ignore:
#+BEGIN_SRC R :exports none :results silent :session
# set variables
#+END_SRC

** Author
Philipp Homan <phoman1 at northwell dot edu>

** Getting Started
This repository contains all the data and analysis code to reproduce the
manuscript Making Research Reproducible. These instructions describe how to obtain a copy
of the project up and running on your local machine for reproducing the
analysis described in the manuscript. The repository contains a Makefile
which reflects the dependencies of the analysis; analysis, figures and
manuscript can be produced by simply typing 'make' from the Unix command
line.
 
*** Prerequisites
**** Code                                             :noexport:ignore:
#+BEGIN_SRC R :exports none :results silent :session
# R version
rvers <- version$version.string

# Python version
# pyvers <- system("python --version")
# pysurfvers <- system("pip freeze | grep pysurf")
#pyvers <- "2.7.13"
#pysurfvers <- "0.7"
pyplusvers <- system("pyv=$(python -V 2>&1); echo $pyv", intern=TRUE)
pysurfplusvers <- system("pip list | grep pysurf", intern=TRUE)
sessInfo <- sessionInfo()
#+END_SRC

**** Text                                                      :ignore:
All analyses were conducted with the R software src_R[:session]{rvers}
{{{results(R version 3.3.2 (2016-10-31))}}}. Mixed models were estimated
using the lme4 library, src_R[:session]{pyplusvers} {{{results(Python
2.7.13)}}} and src_R[:session]{pysurfplusvers} {{{results(pysurfer
(0.7))}}} were also used. The full session info under R can be found at
the end of this file

** Installing
Clone the repository or download the zip file.

** Running the analysis
Change to the represearch directory and run 'make analysis'.

** Producing the figures
Change to the represearch directory and run 'make figures'. The figures can then
be found in output/figures.

** Producing the manuscript
Change to the represearch directory and run 'make manuscript'. The manuscript
will be in src/.

** Built With
src_bash{lsb_release -sd} {{{results(Ubuntu 17.10)}}} on emacs
src_elisp{emacs-version} {{{results(25.2.2)}}} and org-mode
src_elisp{org-version} {{{results(9.1.7)}}}.

** Session info
#+BEGIN_SRC R :results output :exports results 
sessionInfo()
#+END_SRC

#+RESULTS:
#+begin_example
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.04

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
#+end_example
